### ISSUE TITLE
Limit "Groups" to only show specific speakers?

### ISSUE THREAD

**Issue by daytonturner** [johanfrick/custom-sonos-card#115]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a request

**Describe the solution you'd like**
Curious if there's a way to only show a specific speaker, or speakers, including any that are also grouped together, and not show the other groups.  e.g. I have a handful of speakers:  Kitchen, Living Room, Den, Patio, TV.  I provide entityId for the Kitchen speaker, so it shows up highlighted orange.  If I group Living Room with it, it shows Kitchen + Living Room.  The rest of the speakers display in grey instead of orange.  Basically, I'd like to exclude any speakers that show as grey and only show the orange entry.

**Describe alternatives you've considered**
I've attempted to prevent drawing the other speakers using CSS but cannot find a way to do this effectively.

**Additional context**
Thanks!

**Comment by daytonturner** [comment]
I ended up solving what I was trying to accomplish using a mushroom chips template card, so feel free to close this out if its not something you're interested in.  Ultimately I was just looking for a way to focus on one main room, and show just it, and any other speakers that were grouped in.  That data was ultimately available in an attribute of the media_player entity.

**Comment by johanfrick** [comment]
Good. 
Really curious on your solution, would you be able to share your mushroom chips template yaml?

**Comment by daytonturner** [comment]
This uses a mushroom-chips card and, with a template, looks at a specific entity (Kitchen) and displays its friendly name.  If there are other speakers grouped together with this, it will display all of their friendly names, separated by a +

So, it could look like "Kitchen + Living Room + Patio"

Here's what I did:

```
type: custom:mushroom-chips-card
alignment: end
chips:
  - type: template
    entity: media_player.kitchen
    icon: mdi:speaker
    content: >
      {% for speaker in states.media_player.kitchen.attributes.group_members
      %}{{states[speaker].attributes.friendly_name}}{% if not loop.last %} +
      {%endif%}{% endfor %}
```
