### ISSUE TITLE
Request: Add predefined volume per speaker in the Sonoscard

### ISSUE THREAD

**Issue by MNLFDF** [johanfrick/custom-sonos-card#127]
I know it’s possible to group predefined speakers in the living room and put them under a button.

But what I miss is the ability to set a predefined volume per speaker as well. For example my homecinema speakers get the volume 3, the kitchen volume 9, erker volume 5, tafel volume 4. I never can set the starting volume anywhere. Now I use the “Soro” app for apple shortcuts to do this, but would be great if the Sonos card could do this as well. Then I can skip on app again.

Can this being add at the V6 version which you are developing now?

**Comment by johanfrick** [comment]
Great suggestion! Will look into this

**Comment by johanfrick** [comment]
@MNLFDF I have created a beta with a suggestion on how to solve this. Instead of presetting a volume level, you can now work with ratios. That will be more versatile and match whatever you set as volume on the base player.

Example config:
```yaml
type: custom:sonos-card
volumeRatios:
  - basePlayer: media_player.biljardrum
    adjustedPlayer: media_player.master_suite
    ratio: 0.5
```
This example would mean that "Master Suite" player always will have 50% volume of "Biljardrum" player.

Let me know how it works for you!

**Comment by MNLFDF** [comment]
@johanfrick Sounds like a plan, but doesn’t solve my startup volume. My Homecinema configuration is part of the living room/kitchen group when I start listening to the radio. But… when I watched TV, the Homecinema config has a volume of 13-14. Way too loud for the radio. When I listen to radio stations, that volume need to be start at 3. Now I use a separate app to set the group and the start volume. This are my speakers within the group and their start volume (which basically stays at this volume whole day).

Homecinema       3
TV (separate Sonos One Stereo set)    3
Erker        5
Tafel         3
Keuken     11

How would you set this starting volume with “Ratio’s” like you have in Beta 6.6? And when I want this config a bit louder, all numbers will go +1.

**Comment by johanfrick** [comment]
You make a good point. I'll give it another think

**Comment by MNLFDF** [comment]
Did a quick test and all volumes are set right. You nailed it 😆 
Will test more tomorrow. Thanks for this. Now I can get rid of all other extra apps.

I don’t know if this is possible already, but can you also set a predefined radio station when selecting a group? So, volumes and a predefined radio station, or other music from the favorites list?

**Comment by johanfrick** [comment]
https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.6-beta3
```yaml
predefinedGroups:
  - name: Kök&Hall
    media: Legendary
    entities:
      - id: media_player.kok
        volume: 10
      - id: media_player.hall
```
Note: this only works if the media is in your sonos favorites list.
