### ISSUE TITLE
Default player not selected when loading card

### ISSUE THREAD

**Issue by squirtbrnr** [johanfrick/custom-sonos-card#133]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v6.0
**Last working release (if known):**
v5.20.1
**Browser and Operating System:**
W10 - Chrome
iOS 16.5 - HA Companion App

I have a specific speaker set to always load when the card opens.  However, the first sonos speaker in alphabetical order is what is displayed.  Happens on all computers/devices I have tried this on.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
UI raw configuration editor has this:
```
views:
  - title: Sonos Controller
    icon: mdi:speaker
    type: panel
    cards:
      - type: custom:sonos-card
        entityId: media_player.living_room
        labelWhenNoMediaIsSelected: No media selected
        labelForTheAllVolumesSlider: All volumes
        mediaArtworkOverrides:
          - mediaTitleEquals: TV
            imageUrl: https://cdn-icons-png.flaticon.com/512/716/716429.png
            sizePercentage: 40
          - mediaContentIdEquals: x-sonos-htastream:RINCON_949F3EC2E15B01400:spdif
            imageUrl: https://cdn-icons-png.flaticon.com/512/4108/4108783.png
          - ifMissing: true
            imageUrl: https://cdn-icons-png.flaticon.com/512/651/651758.png
        customSources:
          media_player.bedroom:
            - title: TV
              thumbnail: https://cdn-icons-png.flaticon.com/512/716/716429.png
          media_player.front_room:
            - title: TV
              thumbnail: https://cdn-icons-png.flaticon.com/512/716/716429.png
          media_player.living_room:
            - title: TV
              thumbnail: https://cdn-icons-png.flaticon.com/512/716/716429.png
        dynamicVolumeSlider: false
title: Sonos Controller
```
