### ISSUE TITLE
README sample has invalid show_name and show_icon variables in the entities list 

### ISSUE THREAD

**Issue by abanck** [johanfrick/custom-sonos-card#146]
Not relevant for the sonos-card functionality, the stack based sample yaml in the readme has an entities card with a button entity. The sample has two variables show_name and show_icon that are [not supported by the entities list](https://www.home-assistant.io/dashboards/entities/#entities). Due to this the UI gives errors when adding the sample to a dashboard and opening the vertical stack in the visual editor.
Icon and name are shown for the button by default so these variables can be removed without any functional changes. 

```
      - type: entities
        entities:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
```

Also note the sample has overlapping section when adding to a default Masonry style dashboard, not directly clear to me how to fix this
