### ISSUE TITLE
customThumbnailIfMissing only useful if Favorite has no URL, not when the URL is bad or you don't like it

### ISSUE THREAD

**Issue by maddox** [johanfrick/custom-sonos-card#167]
**Is your feature request related to a problem? Please describe.**

I have some favorites where the images just don't load. These are usually Apple Music custom playlists shared with Sonos. These playlist image URLs (still after all these years) use expiring S3 URLs, which work long enough for Sonos to cache them locally, but when used with other tools, fail.

So for these cases, they do have URLs, they're just not working. So the `customThumbnailIfMissing` config does not kick in.

**Describe the solution you'd like**

I'd like this setting (or a new one) to completely override a Favorite's art. If it's defined in the config, use that instead of what Sonos is using.

**Comment by johanfrick** [comment]
You can use mediaArtworkOverrides for this. Below is from [the README](https://github.com/johanfrick/custom-sonos-card/blob/master/README.md#configuration-in-yaml):
```yaml
mediaArtworkOverrides: # Show your own selected artwork if certain rules match
  - mediaTitleEquals: TV
    imageUrl: https://cdn-icons-png.flaticon.com/512/716/716429.png
    sizePercentage: 40
  - mediaContentIdEquals: "x-sonos-htastream:RINCON_949F3EC2E15B01400:spdif"
    imageUrl: https://cdn-icons-png.flaticon.com/512/4108/4108783.png
  - mediaTitleEquals: p4malmo-aac-192
    imageUrl: >-
      https://mytuner.global.ssl.fastly.net/media/tvos_radios/2BDTPrpMbn_cTdteqo.jpg
```
