### ISSUE TITLE
Favorites from Sonos not showing

### ISSUE THREAD

**Issue by mhoogenbosch** [johanfrick/custom-sonos-card#257]
Using latest version of both HA core and Sonos-card (respectively 2023.12.3 and 6.12.4)

With following code on my Windows 11 device, it shows only Spotify and Sonos, thus not showing Reolink, My media and Frigate. This is what I'd like it to have.
```
type: custom:sonos-card
sections:
  - player
  - media browser
widthPercentage: 100
mediaArtworkOverrides:
  - mediaTitleEquals: TV
    imageUrl: https://cdn-icons-png.flaticon.com/512/716/716429.png
    sizePercentage: 40
mediaBrowserTitlesToIgnore:
  - Reolink
  - My media
  - Frigate
topFavorites:
  - 360 Dance
  - Techno Bunker
mediaBrowserItemsPerRow: 1
showVolumeUpAndDownButtons: true
mediaBrowserShowTitleForThumbnailIcons: true
numberOfFavoritesToShow: 5
```
Screenshot of Windows 11:

![image](https://github.com/johanfrick/custom-sonos-card/assets/36899598/970aae23-0865-43f6-95e7-71c7db9a3b9a)

On both my Android 12 and iOS 17.2.1 device, it doesn't seem to be working:

![Afbeelding van WhatsApp op 2023-12-27 om 12 04 33_a44b98af](https://github.com/johanfrick/custom-sonos-card/assets/36899598/75a3adfb-a973-40a3-9dc6-25a9f1bac161)
