### ISSUE TITLE
Unwanted speakers being controlled when controlling one speaker

### ISSUE THREAD

**Issue by m90att** [johanfrick/custom-sonos-card#275]
**Checklist:**

- [Y] I updated to the latest version available
- [Y] I cleared the cache of my browser

**Release with the issue:**
v6.15.3 but it's been here for quite a while before this version

**Last working release (if known):**

**Browser and Operating System:**
Android companion app
Web browsers, edge, chrome, firefox

**Description of problem:**
I have cards defined for specific rooms - the intention is for the cards to only control the speakers in the specific room - but using the card operates other speakers in the house.

One example, this morning, I played a favorite on media_player.study and the favorite was also played on media_player.kitchen and media_player.bathroom.  These devices are not linked in the sonos app either.  I stopped the music playing in kitchen and bathroom and tried again.  This time the favorite was played in study (intended) but also in the bathroom.

The card code for study is below (I have included the full code for the containing item):

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#media_study'
    name: Study
    icon: mdi:speaker
    entity: null
    state: null
    state_unit: null
    width_desktop: 600px
    margin_top_mobile: 18px
    margin_top_desktop: 74px
    trigger_entity: null
    trigger_state: 'on'
    close_on_click: false
  - type: custom:sonos-card
    entityId: media_player.study
    sections:
      - player
      - volumes
      - groups
      - grouping
      - media browser
    mediaBrowserItemsPerRow: 3
    entities:
      - media_player.study
    topFavorites:
      - ''
    hideGroupCurrentTrack: false
    dynamicVolumeSlider: true
    hideBrowseMediaButton: true
    showVolumeUpAndDownButtons: true
```
Note, I have also tried without the media_player.study in the entities section.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
