### ISSUE TITLE
Cant get Sonos player to show

### ISSUE THREAD

**Issue by hwikene** [johanfrick/custom-sonos-card#3]
Hi! Trying to test you Sonos card. But cant get anything to show. 
This is my code: 
```
type: custom:custom-sonos-card
name: Sonos
groupsTitle: ''
groupingTitle: ''
favoritesTitle: Test
headerImage: ''
entities:
  - media_player.sonos_roam
  - media_player.living_room
```

This is what i see: 
![image](https://user-images.githubusercontent.com/17985923/151757432-d2bb877a-85e8-4015-a1e9-479e35809e2e.png)

**Comment by mfabiani53** [comment]
Same issue here....
Installed resource, add the card following the instructions, restarted HA but nothing appears in lovelace...

**Comment by cgeroldinger** [comment]
Same for me

**Comment by giuliandenicola1** [comment]
Might be because of a typo, if one entity is wrong it will show nodig
```
  - media_player.sonos_roam <---
  - media_player.living_room
```

**Comment by Geheim49** [comment]
Same issue for me

**Comment by mbrihed** [comment]
Same here

**Comment by christophermichaelshaw** [comment]
I too am having this issue -- Running Home Assistant 2022.2.0b6.
Attempting to use with 2 Sonos Roams, Sonos Playbar/Sub/Ikea Symphonisk surround group, 2 syphonisk bookshelf.

**Comment by mfabiani53** [comment]
I am asking why some users have it working and many others no....

**Comment by Neu-Bob** [comment]
No luck for me either

Tried to minimize the config so it's only showing 2 of my device and removed options.  nothing showing.

**Comment by mfabiani53** [comment]
I only hope the developer will read these messages....

**Comment by Geheim49** [comment]
> Same issue for me

I feel so dump. I had placed the wrong entity.
Got it working with the following;

`type: custom:custom-sonos-card
name: Sonos
groupsTitle: ''
groupingTitle: ''
favoritesTitle: ''
headerImage: ''
entities:
  - media_player.living_room
`

**Comment by cgeroldinger** [comment]
I tried a couple times. Still a blank screen. Hmmmm
Weird thing…..works fine on my spare setup. Just not on my main one.  Very strange

**Comment by mfabiani53** [comment]
Did you set the card as a new view? If yes, disable all except icon and panel.
In this way i have the card working:
```
  - title: Sonos
    icon: mdi:music-box-multiple-outline
    panel: true
    cards:
      - type: custom:custom-sonos-card
        name: Sonos
        groupsTitle: ''
        groupingTitle: ''
        favoritesTitle: ''
        entities:
          - media_player.studio
          - media_player.sonos
 ````

**Comment by hwikene** [comment]
> Did you set the card as a new view? If yes, disable all except icon and panel.
> 
> In this way i have the card working:
> 
> ```
> 
>   - title: Sonos
> 
>     icon: mdi:music-box-multiple-outline
> 
>     panel: true
> 
>     cards:
> 
>       - type: custom:custom-sonos-card
> 
>         name: Sonos
> 
>         groupsTitle: ''
> 
>         groupingTitle: ''
> 
>         favoritesTitle: ''
> 
>         entities:
> 
>           - media_player.studio
> 
>           - media_player.sonos
> 
>  ````
> 
> But it's really sloooooooowwwwwww

I tried this. But got the same issue. Nothing is showing.

**Comment by ChirpyTurnip** [comment]
If you are having this problem please also check Issue #7 - Card fails to display when Sonos instance is offline.  ;-)

In my case the card wouldn't display as one of my speakers was offline....

CP.

**Comment by rashmipatel829** [comment]
I was able to get the card to show up by: 

1. adding the card as a module.  This is located in configuration -> dashboards -> 'Resources' tab at top -> click on 'add resource'.
For the url, enter /local/custom-sonos-card.js?v=1.0 
Resource type:  Javascript module, then click 'Create'

2.  Then you can add a custom card in your dashboard using the below (with your changes):

type: custom:custom-sonos-card
name: Sonos #Required
groupsTitle: '' #Optional
groupingTitle: '' #Optional
favoritesTitle: '' #Optional
headerImage: '' #Optional
entities: #Required
  - media_player.sonos_kitchen
  - media_player.sonos_hallway
  - media_player.sonos_bedroom
  - media_player.sonos_livingroom

**Comment by johanfrick** [comment]
Many have had issues due to misspelled player name. This is now handled gracefully by a fix to https://github.com/johanfrick/custom-sonos-card/issues/7.
Hopefully that solves all your problems above 🤞

The Sonos Card works fine as a normal card in default view, but looks probably even better using a panel mode:
```yaml
views:
  - title: Home
    type: panel
    cards:
      - type: custom:custom-sonos-card
        entities:
          - media_player.tv
          - media_player.matrum
          - media_player.kok_svart
          - media_player.hall
          - media_player.badrum_nere
          - media_player.kontor
          - media_player.biljardrum
          - media_player.master_bedroom
```
