### ISSUE TITLE
Works great, but

### ISSUE THREAD

**Issue by MaxRei-dev** [johanfrick/custom-sonos-card#6]
Hi,
Thanks for your work. 
It works great for me.
Is there anyway to Make everything a little bigger ?
I want do have a single "Dashboard" "Panel" an in the actual size it looks a little bit lost.
nice to have would be to see some Cover Arts, change the Names of the Players  etc.

thank you very much.

**Comment by mfabiani53** [comment]
How you made this work? I am trying in every way to have this, but as you can see in the issues many users can't have the card working...
Can you share your card?

**Comment by lloyda** [comment]
I had no problems making it work (but  I do have issues as I have reported).

This is what I have for a config:
```
 - title: Sonos
    panel: true    
    cards:
      - type: custom:custom-sonos-card
        name: Sonos #Required
        groupsTitle: '' #Optional
        groupingTitle: '' #Optional
        favoritesTitle: '' #Optional
        headerImage: '' #Optional
        entities: #Required
          - media_player.dining_room
          - media_player.study
          - media_player.kitchen
          - media_player.lounge
```
