### ISSUE TITLE
CSS Styling: Title Styling Parameters Don't Control All Titles

### ISSUE THREAD

**Issue by SergeantPup** [johanfrick/custom-sonos-card#62]
Issue:
Changing the CSS Style settings under 'title' only appear to be affecting the group and the groupings header.  the 'media' header remains unchanged when any of these settings are changed.

Expected behavior:
Changing the CSS styling settings for title should change all titles on the card including 'media'

```
  title:
    fontSize: 50px
    fontWeight: bold
    textTransform: lowercase
    color: var(--primary-color)
```
![2022-04-19 19_01_00-Overview – Home Assistant](https://user-images.githubusercontent.com/48838594/164115085-78824160-4945-4c55-8692-173b851f889b.png)
