### ISSUE TITLE
Media browser as a list instead of in grid mode

### ISSUE THREAD

**Issue by johanfrick** [johanfrick/custom-sonos-card#70]
### Discussed in https://github.com/johanfrick/custom-sonos-card/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **Schmu1605** May  3, 2022</sup>
is it possible to display the media browser as a list instead of in grid mode?</div>

**Comment by cowboysdude** [comment]
I've written modules for MagicMirror project but I am clueless how the structure works here or I'd be happy to help...

**Comment by johanfrick** [comment]
Please try this beta: https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.6.0-beta-media_list
Add this to your card config to enable list mode:
`mediaBrowserItemsAsList: true`

**Comment by Tioborto** [comment]
Hello @johanfrick , it works for me 👍 but I have some problem with css 
![image](https://user-images.githubusercontent.com/29703972/174134855-d26f0ce4-4e91-4f54-95fa-0984f2806ada.png)

Configuration:
```
        layout:
          mobileThresholdPx: 500
          groups:
            width: 20%
            mobileWidth: 100%
          players:
            width: 30%
            mobileWidth: 100%
```
