### ISSUE TITLE
Ability to stack groups and now playing

### ISSUE THREAD

**Issue by vbtrek** [johanfrick/custom-sonos-card#75]
Would it be possible to have 2 columns, 1 with now playing and groups and the other with the media list?

**Comment by johanfrick** [comment]
Yes it’s possible using the styling options. Check the readme

**Comment by vbtrek** [comment]
Ok, I did spend some time looking at the CSS Styling options, and the edge developer tools. I tried to work out the flex columns, but couldn't work out how to change this to 2 columns.

**Comment by johanfrick** [comment]
Okey, seems it's hard to make it true 2 columns. But this sort of does it, and probably gives you an idea on how to continue tweaking:
```
type: custom:custom-sonos-card
layout:
  groups:
    width: 50%
  players:
    width: 50%
  mediaBrowser:
    width: 50%
  mediaItem:
    width: 25%
styles:
  groups:
    order: 2
  content:
    justifyContent: flex-start
```

![image](https://user-images.githubusercontent.com/26582898/173014501-781e042d-04d3-4095-8a2a-f0c3df18a455.png)
